language: python
sudo: required
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
os:
  - linux
#  - osx
install: "sudo python setup.py install"
